linters:
 enable:
   - deadcode
   - varcheck
   - structcheck
 disable:
   - maligned
 enable-all: true
 disable-all: false
 fast: false
 presets:
   - bugfinder
   - complexity
   - format
   - import
   - metrics
   - performance
   - style
 run:
   - gofmt
   - golint
   - gosec
   - goconst
   - gocyclo
   - dupl
   - interfacer
   - scopelint
   - gocritic
   - prealloc
   - nakedret
   - unconvert
   - misspell
   - lll
   - unparam
   - wsl
   - errcheck
   - govet
   - staticcheck
   - ineffassign
   - typecheck
   - unused
   - structtag
   - exhaustive
   - whitespace
   - forbidigo
   - sqlclosecheck
   - nilerr
   -rowserrcheck
   - gocognit
   - goheader
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   - wrapcheck
   - errorlint
   - errname
   - errwrap
   - lll
   - dupl
   - gocyclo
   - unparam
   - scopelint
   - interfacer
   - unconvert
   - gocritic
   - prealloc
   - nakedret
   - misspell
   - whitespace
   - forbidigo
   - gocognit
   - godot
   - funlen
   - rowserrcheck
   -```
